[package]
name = "puzzle_runner_derive"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "=1.0.103"
quote = "=1.0.42"
regex = "=1.12.2"
syn = { version = "=2.0.109", features = ["full", "extra-traits", "visit"] }

[lints]
workspace = true
